### ISSUE TITLE
GUI hangs after incorrect credential submission

### ISSUE THREAD

**Issue by PhlegethonAcheron** [PacketSurf/ZSpotifyGUI#1]
Every time, after incorrect credentials entered, the GUI hangs. However, this is a problem with the base zspotify app, but it would be nice if there was a way to restart the GUI, or at least the zspotify backend when the librespot incorrect credentials exception is thrown.

**Comment by PacketSurf** [comment]
The librespot repo has fixed a bug that solves this problem. Now you should have no problem with freezes anymore. It also fixed issues with downloads stopping and being unable to connect to the api after a disconnect. Make sure you update librespot using:
```
pip install --upgrade git+https://github.com/kokarare1212/librespot-python
```
