### ISSUE TITLE
the program has stopped working!

### ISSUE THREAD

**Issue by RPGW1ZARD** [PacketSurf/ZSpotifyGUI#7]
Hello, I used this great program for half a year and everything was fine, but for the last few days it stopped working correctly, the download process of the track stops at 88%! as it turned out, not only me, help fix this error

**Comment by mattmofr** [comment]
@RPGW1ZARD 
Try changing CHUNK_SIZE to 65536 instead of 50000 in zs_config.json.
It fixed the issue on my side.
Check out the related issue in zspotify : https://github.com/jsavargas/zspotify/issues/5

**Comment by RPGW1ZARD** [comment]
Great News, yes everything worked thanks to you amigo, thank you so much!

> @RPGW1ZARD Попробуйте изменить CHUNK_SIZE на 65536 вместо 50000 в zs_config.json. Это решило проблему на моей стороне. Проверьте связанную проблему в zspotify: [jsavargas/zspotify#5](https://github.com/jsavargas/zspotify/issues/5)

Great News, yes everything worked thanks to you Amigo, thank you so much!!!

**Comment by RPGW1ZARD** [comment]
> @RPGW1ZARD Try changing CHUNK_SIZE to 65536 instead of 50000 in zs_config.json. It fixed the issue on my side. Check out the related issue in zspotify : [jsavargas/zspotify#5](https://github.com/jsavargas/zspotify/issues/5)

Great News, yes everything worked thanks to you Amigo, thank you so much!!!
