### ISSUE TITLE
[Bug] Not downloading completely

### ISSUE THREAD

**Issue by rifqigamers** [PacketSurf/ZSpotifyGUI#8]
The gui says "Downloaded" but the terminal shows that its stuck on 88/87% all the time, the song file is downloaded but the last 12/13% part of the song isnt there. (3:01 total playtime which should be 3:11 etc)

**Comment by k9ur** [comment]
I fixed this by changing `CHUNK_SIZE` in `zs_config.json` to 32768.

**Comment by rifqigamers** [comment]
> I fixed this by changing `CHUNK_SIZE` in `zs_config.json` to 32768.

Thanks for replying = ) 
I'll see if it works!

**Comment by roseblackrocks** [comment]
> I fixed this by changing `CHUNK_SIZE` in `zs_config.json` to 32768.

Came here to see if there was a solution. This worked perfectly. Thanks!
